// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuzneIlUuQPzrBMJRe5hxi7dXLOIZI6l4',
    appId: '1:90542325897:web:64548b8120dcff43898658',
    messagingSenderId: '90542325897',
    projectId: 'smart-meter-b7d40',
    authDomain: 'smart-meter-b7d40.firebaseapp.com',
    storageBucket: 'smart-meter-b7d40.appspot.com',
    measurementId: 'G-CSHSQ5HNKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHZxy82crY3rzvZCbHw-ok77V42pDJ8iI',
    appId: '1:90542325897:android:68632a26435ea66b898658',
    messagingSenderId: '90542325897',
    projectId: 'smart-meter-b7d40',
    storageBucket: 'smart-meter-b7d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYrDqv_akMW2oL4WHMgWVg9wjQSIkGm2k',
    appId: '1:90542325897:ios:d72fd3c736d35ed6898658',
    messagingSenderId: '90542325897',
    projectId: 'smart-meter-b7d40',
    storageBucket: 'smart-meter-b7d40.appspot.com',
    iosBundleId: 'com.example.smartmeterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYrDqv_akMW2oL4WHMgWVg9wjQSIkGm2k',
    appId: '1:90542325897:ios:b542178be8751c8e898658',
    messagingSenderId: '90542325897',
    projectId: 'smart-meter-b7d40',
    storageBucket: 'smart-meter-b7d40.appspot.com',
    iosBundleId: 'com.example.smartmeterapp.RunnerTests',
  );
}
